services:
  postgres:
    container_name: zapochat-postgres
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zapochat
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
